eye:
  #通知相关配置
  notify:
    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 SmsNotifyType 枚举值
    sms:
      enable: true
      # 如果是腾讯云短信，则设置active的值tencent
      # 如果是阿里云短信，则设置active的值aliyun
      active: aliyun
      sign: 付费知识平台
      template:
      - name: paySucceed
        templateId: SMS_200690621
      - name: captcha
        templateId: SMS_200875055
      - name: ship
        templateId: SMS_200790052
      - name: refund
        templateId: SMS_200915047
      tencent:
        appid: **********
        appkey: ************************
      aliyun:
        regionId: cn-zhangjiakou
        accessKeyId: ***************
        accessKeySecret: **************************