spring:
  profiles:
    active: db, core, storage, express, mail,sms
  messages:
    encoding: UTF-8

server:
  port: 8090

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.eye.common:  DEBUG

swagger:
  production: false