eye:
  # 开发者应该设置成自己的wx相关信息
  wx:
    app-id: ****************
    app-secret: *********************
    mch-id: *****************
    mch-key: *************************
    notify-url: https://wwwapidev.6eye9.com/common/order/pay-notify
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: file/apiclient_cert.p12





