eye:
  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: aliyun
    # 本地对象存储配置信息
    local:
      storagePath: storage
      # 这个地方应该是common模块的WxStorageController的fetch方法对应的地址
      address: http://localhost:8060/common/storage/fetch/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-zhangjiakou.aliyuncs.com
      accessKeyId: *****************
      accessKeySecret: ******************************
      bucketName: ********
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: AKIDOccMr856uoU1Tsa2MQL5aqseBUWRrb5i
      secretKey: XqtgEhIdrupTs4ygaWlkUUXv3w3FiwuD
      region: ap-shanghai
      bucketName: vytech-1300096589
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://pd5cb6ulu.bkt.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: litemall